name: Build and Run C++ Program

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install C++ Compiler
        run: sudo apt update && sudo apt install -y g++

      - name: Compile Program
        run: g++ -o hello main.cpp

      - name: Run Program
        run: ./hello
